# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: azure-devops-yml-variables

steps:
- task: TerraformInstaller@0
  displayName: 'Terraform installer'
  inputs:
    terraformVersion: 'latest'
- task: TerraformCLI@0
  displayName: 'Initilizer'
  inputs:
    command: 'init'
    backendServiceArm: $(backendServiceArm)
    backendAzureRmResourceGroupName: $(backendAzureRmResourceGroupName)
    backendAzureRmStorageAccountName: $(backendAzureRmStorageAccountName)
    backendAzureRmContainerName: $(backendAzureRmContainerName)
    backendAzureRmKey: $(backendAzureRmKey)
    backendAzureRmResourceGroupLocation: $(backendAzureRmResourceGroupLocation)
   # backendType: $(backendType)
    backendType: azurerm
    ensureBackend: true

- task: TerraformCLI@0
  displayName: 'Validation'
  inputs:
    command: 'validate'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  displayName: 'aero-planner'
  inputs:
    command: 'plan'
    commandOptions: '-out=planresults.tf'
    allowTelemetryCollection: true
    environmentServiceName: $(backendServiceArm)
    publishPlanPublish: 'Plan Results'
- task: TerraformCLI@0
  displayName: 'Apply'
  inputs:
    command: 'apply'
    commandOptions: 'planresults.tf'
    allowTelemetryCollection: true
    environmentServiceName: $(backendServiceArm)





