# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  displayName: 'Terraform installer'
  inputs:
    terraformVersion: 'latest'
- task: TerraformCLI@0
  displayName: 'Initilizer'
  inputs:
    command: 'init'
    backendServiceArm: 'Ab-Azure Sub'
    backendAzureRmResourceGroupName: 'Ab-Terraform-Training'
    backendAzureRmStorageAccountName: 'Abterraformuks'
    backendAzureRmContainerName: 'Abterratrain'
    backendAzureRmKey: 'terraform.tfstate'
    backendAzureRmResourceGroupLocation: 'uksouth'
    backendType: 'azurerm'
    ensureBackend: true 
- task: TerraformCLI@0
  displayName: 'Validation'
  inputs:
    command: 'validate'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  displayName: 'aero-planner'
  inputs:
    command: 'plan'
    allowTelemetryCollection: true
    environmentServiceName: 'Ab-Azure Sub'

- task: TerraformCLI@0
  displayName: 'Apply'
  inputs:
    command: 'apply'
    allowTelemetryCollection: true
    environmentServiceName: 'Ab-Azure Sub'



